### ISSUE TITLE
Mentoring

### ISSUE THREAD

**Issue by Christoph33one** [Christoph33one/Womens-day-Hackathon-2023#12]
- [x] Create a new HTML file (Pick a name of your choosing)
- [x] Add some information as to what the mentoring program is and how to apply (Hannah)
**Here is a link it help you write this up**
https://women-in-tech.org/mentoring-program/

- [x] Add link buttons on the bottom of the home page

- [x] Create a form for a user to view and fill out, with a submit button
**form features**

- [x] First name
- [x] last name
- [x] email address
- [x] contact number (optional)
- [x] Skill set (skills used in. the tech industry)
- [x] Inout field for their bio 
- [x] submit form

A post request should be added after the form is complete.
- [ ]Create a file named - mentor.py

**Comment by bubtroniq** [comment]
done
